export const dummyUsers = [
    { nickname: '폭풍의주인공', tag: 'KR1', weight: 33 },
    { nickname: '탑정글장인', tag: 'KR2', weight: 61 },
    { nickname: '베인장인', tag: '1997', weight: 23 },
    { nickname: '너프좀하자', tag: 'GG', weight: 44 },
    { nickname: '지원이짱', tag: 'SUP', weight: 12 },
    { nickname: '강냉이브레이커', tag: 'KR1', weight: 71 },
    { nickname: '킬각장인', tag: 'KR3', weight: 83 },
    { nickname: '빵야빵야', tag: 'EZ', weight: 1 },
    { nickname: '포탑지킴이', tag: 'KR5', weight: 54 },
    { nickname: '달려라달려', tag: 'RUN', weight: 64 },
    { nickname: '백도어장인', tag: 'BD', weight: 21 },
    { nickname: '그브는못참지', tag: 'GR', weight: 82 },
    { nickname: '블루도둑', tag: 'BLU', weight: 4 },
    { nickname: '탱커킬러', tag: 'TK', weight: 50 },
    { nickname: '물몸대장', tag: 'MM', weight: 72 },
    { nickname: '탑에서탈주', tag: 'AFK', weight: 10 },
    { nickname: '장로먹고던짐', tag: 'ELD', weight: 30 },
    { nickname: '전령몰빵러', tag: 'HER', weight: 62 },
    { nickname: '스플릿러', tag: 'SPL', weight: 43 },
    { nickname: '쌍둥이박살러', tag: 'TWN', weight: 24 },
];
